#!/bin/bash

thing="hello world"
thing2='more $thing'
thing3="more $thing"
thing4=$(ls)
count=$(ls | wc -l)

echo $thing
echo $thing2
echo $thing3
echo $thing4
echo $count
echo "hello world"
echo $0
echo $@
echo $#
echo $1
